skip_branch_with_pr: true

image:
  - Visual Studio 2017

cache:
  - C:\msys64 -> scripts/msys2-install-dependencies.sh

environment:
  APPVEYOR_RDP_PASSWORD:
    secure: XDykCFZ8bK1vmAt5uLpne5RRSUKTVNJnS4ysRGcJ3Is=

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --sync --refresh --sysupgrade
  - C:\msys64\usr\bin\bash -lc /c/projects/openscad/scripts/msys2-install-dependencies.sh
  - C:\msys64\usr\bin\bash -lc "echo 'export PATH=/mingw64/bin:$PATH' > ~/.bashrc"
  - C:\msys64\usr\bin\bash -lc "find /mingw64"

build_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && qmake.exe openscad.pro CONFIG-=debug CONFIG+=experimental CONFIG+=snapshot CONFIG+=info"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && mingw32-make.exe -j2"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && git submodule update --init"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && ls -la"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && /mingw64/bin/cmake.exe --system-information || pwd; sleep 10"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && /mingw64/bin/cmake.exe ."
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && mingw32-make.exe -j2"

test_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && /mingw64/bin/ctest.exe"
