skip_branch_with_pr: true

image:
  - Visual Studio 2017

cache:
  - C:\msys64 -> scripts/msys2-install-dependencies.sh

install:
  - C:\msys64\usr\bin\bash -lc /c/projects/scripts/msys2-install-dependencies.sh
  - C:\msys64\usr\bin\bash -lc "echo 'export PATH=/mingw64/bin:$PATH' > ~/.bashrc"
  - C:\msys64\usr\bin\bash -lc "find /mingw64"

build_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && qmake.exe openscad.pro CONFIG-=debug CONFIG+=experimental CONFIG+=snapshot CONFIG+=info"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && mingw32-make.exe -j2"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && git submodule update --init"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && cmake.exe --system-information"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && cmake.exe ."
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && mingw32-make.exe -j2"

test_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && ctest.exe"
