skip_branch_with_pr: true

image:
  - Visual Studio 2017

#cache:
#  - C:\msys64 -> scripts/msys2-install-dependencies.sh

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - C:\msys64\usr\bin\pacman --query --explicit
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 -Sy
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 -Su
  - C:\msys64\usr\bin\pacman --noconfirm --ask 20 --force -S mingw-w64-x86_64-gdb mingw-w64-x86_64-boost mingw-w64-x86_64-cgal mingw-w64-x86_64-eigen3 mingw-w64-x86_64-glew mingw-w64-x86_64-qscintilla mingw-w64-x86_64-opencsg mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cmake mingw-w64-x86_64-libzip bison git
  - C:\msys64\usr\bin\bash -lc "echo 'export PATH=/mingw64/bin:$PATH' > ~/.bashrc"
  - C:\msys64\usr\bin\bash -lc "find /mingw64"

build_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && qmake.exe openscad.pro CONFIG-=debug CONFIG+=experimental CONFIG+=snapshot CONFIG+=info"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && mingw32-make.exe -j2"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad && git submodule update --init"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && ls -la"
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && /mingw64/bin/cmake.exe -G 'MSYS Makefiles' ."
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && mingw32-make.exe -j2"

test_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/projects/openscad/tests && /mingw64/bin/ctest.exe"
